#!/usr/bin/env perl

my $build_cmd = 'giblog build';
system($build_cmd) == 0
  or warn("Can't execute build command $build_cmd:$!");

use Mojolicious::Lite;

get '/' => sub {
  my $c = shift;
  
  $c->reply->static('index.html');
};

app->start;
