#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename 'dirname';
my $giblog_dir;
BEGIN {
  $giblog_dir = dirname __FILE__;
}
use lib "$giblog_dir/lib";
use Giblog;
use Giblog::Plugin::build;

use Mojolicious::Lite;

my $rebuild;
get '/' => sub {
  my $c = shift;
  
  unless ($rebuild) {
    # Rebuild
    my $start_time = time;

    my $giblog = Giblog->new('giblog-dir' => $giblog_dir);
    my $build_plugin = Giblog::Plugin::build->new(giblog => $giblog);
    $build_plugin->plugin;

    my $build_time = time - $start_time;
    $rebuild = 1;
  }
  
  $c->reply->static('index.html');
};

app->start;
